version: "2.4"
services:
  web:
    build:
      context: .
      dockerfile: QuizPrototype.WebApi/Dockerfile     
    ports:
      - "8888:80"
    environment:
        ConnectionStrings__Default: Server=db-srv; Database=QuizPrototype; User=sa; Password=Top-Secret;
     
    
  db-srv:
    image: custom-sql-server
    build: Database
    ports:
      - 14331:1433
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: Top-Secret
        MSSQL_PID: Developer
    healthcheck:
        test: nc -z localhost 1433 || exit -1
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 20s