Create database QuizGame
GO
Use QuizGame
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Test](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Text] [varchar](100) NOT NULL,
	[AbtNr] [int] NOT NULL	
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO