Create database QuizPrototype
GO
Use QuizPrototype
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Frage](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FrageText] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Auswahl](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[AuswahlText] [varchar](255) NOT NULL,
	[Order] [int] NOT NULL,
	[FrageId] [bigint] NOT NULL		
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO